### ISSUE TITLE
.contains() method

### ISSUE THREAD

**Issue by conorgil** [onechiporenko/chai-string#11]
It would be really useful to have a `.contains(str, substr)` method to improve readability. Currently, I have to use `assert(str.indexOf(substr) > 0)`, which does read as nicely.

Thoughts?

**Comment by onechiporenko** [comment]
Hi, @conorgil.
It's already implemented in the chai.js
http://chaijs.com/api/assert/#method_include
http://chaijs.com/api/bdd/#method_include
