### ISSUE TITLE
.to.includes

### ISSUE THREAD

**Issue by darlanmendonca** [onechiporenko/chai-string#14]
hey man, nice module!!

what you think to add a method to assert if string includes another?

following the native method [includes](https://www.w3schools.com/jsref/jsref_includes.asp) from String

**Comment by onechiporenko** [comment]
Hi, @darlanmendonca.
I think, it's already  implemented in chai:
https://github.com/onechiporenko/chai-string/issues/11#issuecomment-248914233

**Comment by darlanmendonca** [comment]
yeah, you're right, exists a chainable `.include` and can be used to strings or arrrays, etc.

thanks, I had not seen it before

:D
