### ISSUE TITLE
`startsWith` doesn’t work with `that`

### ISSUE THREAD

**Issue by lo1tuma** [onechiporenko/chai-string#5]
`that` changes the assertion subject of a property assertion.

For example:
```js
var obj = { foo: 'hello world' };
expect(obj).to.have.property('foo').that.is.a('string');
```

This works fine, but if I use `startsWith` on changed assertion subject like in the following example, I get an error.

```js
var obj = { foo: 'hello world' };
expect(obj).to.have.property('foo').that.startsWith('hello');
```

Error:
````
 TypeError: undefined is not a function
      at Object.chai.string.startsWith (workspace/restling/node_modules/chai-string/chai-string.js:23:16)
```

**Comment by onechiporenko** [comment]
Hi! Thanks for bug-report.
Going to work on it.

**Comment by onechiporenko** [comment]
I've tested your example locally and it works for me.
`chai-string.js:23:16` - it's a start of `indexOf`-call.
For some reason, this method isn't defined for your string.

**Comment by lo1tuma** [comment]
You are right, after updating all my dependencies I can’t reproduce this any more.

Thanks for taking a look.

**Comment by chovy** [comment]
this doesn't work for me:

```
    expect(item).to.have.property('url')
      .that.is.a('string')
      .and.startsWith('http');
```

**Comment by chovy** [comment]
nevermind. didn't realize this was a chai plugin. installing and using it solved my problem.
